# Generated by Django 4.2 on 2023-04-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_address_line2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.TextField(default='null'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('pub_date', models.DateField()),
                ('no_pages', models.IntegerField()),
                ('book_lang', models.CharField(max_length=400)),
                ('book_dim', models.CharField(max_length=200)),
                ('book_isbn10', models.CharField(default=0, max_length=400)),
                ('book_isbn13', models.CharField(default=0, max_length=400)),
                ('book_image', models.ImageField(upload_to='book_upload_to')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.author')),
            ],
        ),
    ]
