# Generated by Django 4.2 on 2023-04-19 17:38

from django.db import migrations, models
import library_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_members_options_alter_address_line2_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to=library_app.models.book_upload_to),
        ),
    ]
