# Generated by Django 4.2 on 2023-05-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_alter_address_mobileno_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.AddField(
            model_name='student',
            name='fullname',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookissued',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.student', to_field='fullname'),
        ),
        migrations.CreateModel(
            name='BookReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datereturned', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.student')),
            ],
            options={
                'verbose_name_plural': 'Books Returned',
            },
        ),
    ]
