# Generated by Django 4.2 on 2023-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_student_password_student_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissued',
            name='stud_id',
            field=models.IntegerField(default=0),
        ),
    ]
