# Generated by Django 4.2 on 2023-05-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_bookissued_stud_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreturned',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreturned',
            name='student',
        ),
        migrations.AddField(
            model_name='bookreturned',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookreturned',
            name='book_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookreturned',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookreturned',
            name='student_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
