# Generated by Django 4.2 on 2023-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0014_remove_bookreturned_book_remove_bookreturned_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=400)),
                ('book_image', models.TextField()),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Requested Books',
            },
        ),
    ]
