# Generated by Django 4.2 on 2023-09-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0016_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_image',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.TextField(default=''),
        ),
    ]
