# Generated by Django 4.2 on 2023-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0017_remove_author_author_image_alter_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.TextField(default=''),
        ),
    ]
