# Generated by Django 4.2 on 2023-09-18 00:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0018_author_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
